### 登录
POST {{baseUrl}}/admin/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

> {%
    client.test("登录成功", function () {

        client.global.set("Authorization", "bearer " + response.body.data.token);
    })
%}


### 文章-列表
GET {{baseUrl}}/admin/post
Authorization: {{Authorization}}


### 文章-详情
GET {{baseUrl}}/admin/post/1


### 文章-新增
POST {{baseUrl}}/admin/post
Authorization: {{Authorization}}
Content-Type: application/json

{
  "title": "test2",
  "description": "a test post",
  "tagIds": [1, 2, 3],
  "draft": false,
  "content": "testtesttesttesttesttesttesttesttesttest"
}



### 标签-所有
GET {{baseUrl}}/admin/tag/all
Authorization: {{Authorization}}



### 标签-新增
POST {{baseUrl}}/admin/tag
Authorization: {{Authorization}}
Content-Type: application/json

{
  "name": "test5"
}

### 标签-修改
PUT {{baseUrl}}/sys/tag
Authorization: {{Authorization}}
Content-Type: application/json

{
  "id": 1,
  "name": "testt"
}

### 标签-列表
GET {{baseUrl}}/sys/tag
Authorization: {{Authorization}}